import type { Field } from "../src/lib/Model";
export const mockFields = [
  {
    id: "_3zf6udtk",
    position: [0, 0],
    isTable: false,
  },
  {
    id: "_yl8mvwtb",
    position: [1, 0],
    isTable: false,
  },
  {
    id: "_ymuihu3",
    position: [2, 0],
    isTable: false,
  },
  {
    id: "_5vwy6vyvd",
    position: [3, 0],
    isTable: false,
  },
  {
    id: "_zpiibd7",
    position: [4, 0],
    isTable: false,
  },
  {
    id: "_zn46k7c",
    position: [5, 0],
    isTable: false,
  },
  {
    id: "_yabe0gm",
    position: [6, 0],
    isTable: false,
  },
  {
    id: "_1xwt12zf",
    position: [7, 0],
    isTable: false,
  },
  {
    id: "_u05zmaii",
    position: [8, 0],
    isTable: false,
  },
  {
    id: "_3vzobyzb",
    position: [9, 0],
    isTable: false,
  },
  {
    id: "_j9r8vk7a",
    position: [0, 1],
    isTable: false,
  },
  {
    id: "_fkt5517h",
    position: [1, 1],
    isTable: true,
    student: {
      id: "_gzkdmthi",
      name: "Mathilda",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_2b5bhw19",
    position: [2, 1],
    isTable: true,
    student: {
      id: "_00w3pgvl",
      name: "Henriette",
      forbiddenNeighbors: [],
      alone: false,
      row: "first",
    },
  },
  {
    id: "_lmetrm9",
    position: [3, 1],
    isTable: true,
    student: {
      id: "_slke8tan",
      name: "Stephanie",
      forbiddenNeighbors: [],
      alone: false,
      row: "first",
    },
  },
  {
    id: "_24zwics9",
    position: [4, 1],
    isTable: true,
    student: {
      id: "_nau0n3nm",
      name: "Kurt",
      forbiddenNeighbors: ["Henry", "Math", "Hilda"],
      alone: false,
    },
  },
  {
    id: "_1h2y6a3q",
    position: [5, 1],
    isTable: true,
    student: {
      id: "_uamx17u",
      name: "Markus",
      forbiddenNeighbors: ["Jette", "Henriette"],
      alone: false,
      row: "first",
    },
  },
  {
    id: "_x5oosoqg",
    position: [6, 1],
    isTable: true,
    student: {
      id: "_xio04cb",
      name: "Henry",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_6pb1yvm",
    position: [7, 1],
    isTable: true,
    student: {
      id: "_oqx0d4jo",
      name: "Jette",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_t24wnbpq",
    position: [8, 1],
    isTable: true,
    student: {
      id: "_4ggbg8k9",
      name: "Math",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_pqupuh9",
    position: [9, 1],
    isTable: false,
  },
  {
    id: "_yf4qleyo",
    position: [0, 2],
    isTable: false,
  },
  {
    id: "_o2evznqc",
    position: [1, 2],
    isTable: false,
  },
  {
    id: "_f91njntk",
    position: [2, 2],
    isTable: false,
  },
  {
    id: "_uffly24a",
    position: [3, 2],
    isTable: false,
  },
  {
    id: "_94xl2wa",
    position: [4, 2],
    isTable: false,
  },
  {
    id: "_gq91ccce",
    position: [5, 2],
    isTable: false,
  },
  {
    id: "_du8h16km",
    position: [6, 2],
    isTable: false,
  },
  {
    id: "_oexz6eac",
    position: [7, 2],
    isTable: false,
  },
  {
    id: "_zuml95v",
    position: [8, 2],
    isTable: false,
  },
  {
    id: "_qtpklz1e",
    position: [9, 2],
    isTable: false,
  },
  {
    id: "_wtivhbck",
    position: [0, 3],
    isTable: false,
  },
  {
    id: "_r9ck5fr",
    position: [1, 3],
    isTable: true,
    student: {
      id: "_lvzvv1vp",
      name: "Hilda",
      forbiddenNeighbors: ["Markus", "Stephanie"],
      alone: false,
      row: "first",
    },
  },
  {
    id: "_xwyp6ju",
    position: [2, 3],
    isTable: true,
    student: {
      id: "_e7b8f397",
      name: "hanni",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_e05lwqz9",
    position: [3, 3],
    isTable: true,
    student: {
      id: "_bwc2ye8",
      name: "nanni",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_dy999otd",
    position: [4, 3],
    isTable: true,
    student: {
      id: "_0geccz2h",
      name: "randu",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_l7r8pcsh",
    position: [5, 3],
    isTable: true,
    student: {
      id: "_ukqkrls",
      name: "nandu",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_gbt1y58",
    position: [6, 3],
    isTable: true,
    student: {
      id: "_wn9ijrqv",
      name: "expert",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_nb7ena54",
    position: [7, 3],
    isTable: true,
    student: {
      id: "_0w3h0lsx",
      name: "gunni",
      forbiddenNeighbors: [],
      row: "last",
      alone: false,
    },
  },
  {
    id: "_btq1ldyl",
    position: [8, 3],
    isTable: true,
    student: {
      id: "_rs1j6m5g",
      name: "ganni",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_8s3yd1tk",
    position: [9, 3],
    isTable: false,
  },
  {
    id: "_ohxoehmh",
    position: [0, 4],
    isTable: false,
  },
  {
    id: "_xbburaz",
    position: [1, 4],
    isTable: false,
  },
  {
    id: "_jk3tqj3g",
    position: [2, 4],
    isTable: false,
  },
  {
    id: "_y5i9dus8f",
    position: [3, 4],
    isTable: false,
  },
  {
    id: "_kq1faz1",
    position: [4, 4],
    isTable: false,
  },
  {
    id: "_1mxrgbzww",
    position: [5, 4],
    isTable: false,
  },
  {
    id: "_1uxemy9d",
    position: [6, 4],
    isTable: false,
  },
  {
    id: "_373fxph3",
    position: [7, 4],
    isTable: false,
  },
  {
    id: "_xgh54mwv",
    position: [8, 4],
    isTable: false,
  },
  {
    id: "_myparkz2",
    position: [9, 4],
    isTable: false,
  },
  {
    id: "_1hx9e16s",
    position: [0, 5],
    isTable: false,
  },
  {
    id: "_t1u78bs",
    position: [1, 5],
    isTable: true,
    student: {
      id: "_4lbfvy8a",
      name: "herbert",
      forbiddenNeighbors: [],
      row: "last",
      alone: false,
    },
  },
  {
    id: "_r74k1ic4",
    position: [2, 5],
    isTable: true,
    student: {
      id: "_qbrpodhs",
      name: "ferbert",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_d3abppn3",
    position: [3, 5],
    isTable: true,
    student: {
      id: "_ey8y85b",
      name: "furz",
      forbiddenNeighbors: [],
      row: "last",
      alone: false,
    },
  },
  {
    id: "_1vtcz1z8",
    position: [4, 5],
    isTable: true,
    student: {
      id: "_rluzliz",
      name: "kurz",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_xa0i3brp",
    position: [5, 5],
    isTable: true,
    student: {
      id: "_q25rya",
      name: "murz",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_ffkvo5vc",
    position: [6, 5],
    isTable: true,
    student: {
      id: "_sinbbdtb",
      name: "burz",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_3foanjwz",
    position: [7, 5],
    isTable: true,
    student: {
      id: "_plka0sia",
      name: "ehne",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_rv4tw1q",
    position: [8, 5],
    isTable: true,
    student: {
      id: "_dt40y0qs",
      name: "reiner",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_zz9h2te",
    position: [9, 5],
    isTable: true,
    student: {
      id: "_ejtvkdeg",
      name: "rainier",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_7vfnbc6eo",
    position: [0, 6],
    isTable: false,
  },
  {
    id: "_ag08nzll",
    position: [1, 6],
    isTable: false,
  },
  {
    id: "_8s9tfslk",
    position: [2, 6],
    isTable: false,
  },
  {
    id: "_1t4gmsfd",
    position: [3, 6],
    isTable: false,
  },
  {
    id: "_gfm7cr1",
    position: [4, 6],
    isTable: false,
  },
  {
    id: "_ah4lpake",
    position: [5, 6],
    isTable: false,
  },
  {
    id: "_cvevttlg",
    position: [6, 6],
    isTable: false,
  },
  {
    id: "_ek2wnyn27",
    position: [7, 6],
    isTable: false,
  },
  {
    id: "_yl1yti5q",
    position: [8, 6],
    isTable: false,
  },
  {
    id: "_c43opzzc",
    position: [9, 6],
    isTable: false,
  },
  {
    id: "_0qfpwyq1",
    position: [0, 7],
    isTable: false,
  },
  {
    id: "_l5n0v4ue",
    position: [1, 7],
    isTable: true,
    student: {
      id: "_aqbqrna5",
      name: "bello",
      forbiddenNeighbors: [],
      alone: false,
    },
  },
  {
    id: "_z0df72nl",
    position: [2, 7],
    isTable: true,
  },
  {
    id: "_1ewo2lob",
    position: [3, 7],
    isTable: true,
  },
  {
    id: "_i7035z7",
    position: [4, 7],
    isTable: true,
  },
  {
    id: "_0mio20t8",
    position: [5, 7],
    isTable: true,
  },
  {
    id: "_2jnlh7g",
    position: [6, 7],
    isTable: true,
  },
  {
    id: "_isgfhja",
    position: [7, 7],
    isTable: true,
  },
  {
    id: "_atvk8wr",
    position: [8, 7],
    isTable: false,
  },
  {
    id: "_j6xla1ou",
    position: [9, 7],
    isTable: false,
  },
  {
    id: "_25i38o3e",
    position: [0, 8],
    isTable: false,
  },
  {
    id: "_f41v8rzy",
    position: [1, 8],
    isTable: false,
  },
  {
    id: "_t6yvmmtj",
    position: [2, 8],
    isTable: false,
  },
  {
    id: "_ux1ezfj7",
    position: [3, 8],
    isTable: false,
  },
  {
    id: "_lmny3tva",
    position: [4, 8],
    isTable: false,
  },
  {
    id: "_jrzaayh2",
    position: [5, 8],
    isTable: false,
  },
  {
    id: "_5z0pijrb",
    position: [6, 8],
    isTable: false,
  },
  {
    id: "_t97geivt",
    position: [7, 8],
    isTable: false,
  },
  {
    id: "_3xbj67c7",
    position: [8, 8],
    isTable: false,
  },
  {
    id: "_pk3drct",
    position: [9, 8],
    isTable: false,
  },
  {
    id: "_56txxuqh",
    position: [0, 9],
    isTable: false,
  },
  {
    id: "_oz8mrtzi",
    position: [1, 9],
    isTable: false,
  },
  {
    id: "_9yjrh69n",
    position: [2, 9],
    isTable: false,
  },
  {
    id: "_4wcufoy",
    position: [3, 9],
    isTable: false,
  },
  {
    id: "_98pu11ub",
    position: [4, 9],
    isTable: false,
  },
  {
    id: "_5xpintcw",
    position: [5, 9],
    isTable: false,
  },
  {
    id: "_9jc0tov",
    position: [6, 9],
    isTable: false,
  },
  {
    id: "_ikwmzyy9",
    position: [7, 9],
    isTable: false,
  },
  {
    id: "_gshwls59",
    position: [8, 9],
    isTable: false,
  },
  {
    id: "_7mwzlfjl",
    position: [9, 9],
    isTable: false,
  },
] as Field[];
