// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type Room struct {
	ID   int32
	Name sql.NullString
}

type Session struct {
	ID        int32
	UserID    int32
	TokenHash string
}

type Student struct {
	ID      int32
	Name    string
	TribeID sql.NullInt32
}

type StudentTableSubject struct {
	StudentID int32
	TableID   int32
	SubjectID int32
}

type Subject struct {
	ID        int32
	Name      string
	TeacherID sql.NullInt32
	TribeID   sql.NullInt32
	RoomID    sql.NullInt32
}

type Table struct {
	ID       int32
	RoomID   sql.NullInt32
	Position interface{}
}

type Tribe struct {
	ID            int32
	Name          sql.NullString
	HeadTeacherID sql.NullInt32
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Role         sql.NullString
}
