// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Constraint struct {
	ID                int64
	StudentID         sql.NullInt64
	TeacherID         sql.NullInt64
	SubjectID         sql.NullInt64
	Alone             sql.NullBool
	ForbiddenStudents []int64
}

type Student struct {
	ID      int64
	Name    string
	Gender  sql.NullString
	TribeID sql.NullInt64
}

type StudentSubject struct {
	StudentID int64
	SubjectID int64
	Position  interface{}
}

type Subject struct {
	ID        int64
	Name      string
	TeacherID sql.NullInt64
	TribeID   sql.NullInt64
}

type Tribe struct {
	ID        int64
	Name      sql.NullString
	TeacherID sql.NullInt64
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         sql.NullString
}
